TORCH_DISTRIBUTED_DEBUG=DETAIL CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6" torchrun --nproc_per_node 7 -m training.main \
    --save-frequency 1 \
    --zeroshot-frequency 1 \
    --report-to tensorboard \
    --train-data="/mnt/hdd8/yicheng/daclip-uir/universal-image-restoration/datasets_1/train/train/merged_daclip_train.csv"  \
    --val-data="/mnt/hdd8/yicheng/daclip-uir/universal-image-restoration/datasets_1/train/val/merged_daclip_train.csv"  \
    --csv-img-key filepath \
    --csv-caption-key title \
    --warmup 100 \
    --batch-size=512 \
    --lr=2e-5 \
    --wd=0.05 \
    --epochs=200 \
    --workers=4 \
    --model daclip_ViT-B-32 \
    --name "daclip_ViT-B-32-$(date +%Y%m%d%H%M%S)" \
    --pretrained "laion2b_s34b_b79k" \
    --da
