CUDA_VISIBLE_DEVICES=0 python -m training.main \
    --save-frequency 1 \
    --zeroshot-frequency 1 \
    --report-to tensorboard \
    --train-data="/mnt/hdd7/yicheng/daclip-uir/universal-image-restoration/datasets/test/train/daclip_train_final.csv"  \
    --val-data="/mnt/hdd7/yicheng/daclip-uir/datasets/DIV2K_daclip_val/daclip_val.csv"  \
    --csv-img-key filepath \
    --csv-caption-key title \
    --warmup 100 \
    --batch-size=2 \
    --lr=2e-5 \
    --wd=0.05 \
    --epochs=200 \
    --workers=8 \
    --model daclip_ViT-B-32 \
    --name "daclip_ViT-B-32-$(date +%Y%m%d%H%M%S)" \
    --pretrained "laion2b_s34b_b79k" \
    --da
